api_platform:
    title: 'API Gestion des Notes'
    version: '1.0.0'
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    docs_formats:
        html: ['text/html']
        json: ['application/json']