framework:
  secret: "%env(APP_SECRET)%"
  annotations: false
  http_method_override: false
  handle_all_throwables: true

  assets:
    json_manifest_path: null

  session:
    # Use our PDO session handler
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native
    name: SYMFONY_SESS
    cookie_httponly: true
    save_path: null

  php_errors:
    log: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
