# config/packages/knp_snappy.yaml
knp_snappy:
    pdf:
        enabled: true
        binary: '"C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe"'
        options:
            no-outline: true
            margin-top: 10mm
            margin-bottom: 10mm
            margin-left: 10mm
            margin-right: 10mm
    image:
        enabled: true
        binary: "C:/Program Files/wkhtmltopdf/bin/wkhtmltoimage.exe"